version: '3.8'
services:
  db:
    image: postgres:latest
    user: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data/"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

volumes:
  dbdata:
